// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/cliente.proto

package cliente

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClienteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre     string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Edad       int32  `protobuf:"varint,2,opt,name=edad,proto3" json:"edad,omitempty"`
	Facultad   string `protobuf:"bytes,3,opt,name=facultad,proto3" json:"facultad,omitempty"`
	Disciplina int32  `protobuf:"varint,4,opt,name=disciplina,proto3" json:"disciplina,omitempty"`
}

func (x *ClienteRequest) Reset() {
	*x = ClienteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cliente_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClienteRequest) ProtoMessage() {}

func (x *ClienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cliente_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClienteRequest.ProtoReflect.Descriptor instead.
func (*ClienteRequest) Descriptor() ([]byte, []int) {
	return file_proto_cliente_proto_rawDescGZIP(), []int{0}
}

func (x *ClienteRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *ClienteRequest) GetEdad() int32 {
	if x != nil {
		return x.Edad
	}
	return 0
}

func (x *ClienteRequest) GetFacultad() string {
	if x != nil {
		return x.Facultad
	}
	return ""
}

func (x *ClienteRequest) GetDisciplina() int32 {
	if x != nil {
		return x.Disciplina
	}
	return 0
}

type ClienteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *ClienteResponse) Reset() {
	*x = ClienteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cliente_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClienteResponse) ProtoMessage() {}

func (x *ClienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cliente_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClienteResponse.ProtoReflect.Descriptor instead.
func (*ClienteResponse) Descriptor() ([]byte, []int) {
	return file_proto_cliente_proto_rawDescGZIP(), []int{1}
}

func (x *ClienteResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_proto_cliente_proto protoreflect.FileDescriptor

var file_proto_cliente_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x22, 0x78,
	0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x64, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x65, 0x64, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x61, 0x63, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x61, 0x63, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63,
	0x69, 0x70, 0x6c, 0x69, 0x6e, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69,
	0x73, 0x63, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x61, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x6e, 0x73, 0x61, 0x6a, 0x65, 0x32, 0x54, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0d, 0x45, 0x6e, 0x76, 0x69, 0x61,
	0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_cliente_proto_rawDescOnce sync.Once
	file_proto_cliente_proto_rawDescData = file_proto_cliente_proto_rawDesc
)

func file_proto_cliente_proto_rawDescGZIP() []byte {
	file_proto_cliente_proto_rawDescOnce.Do(func() {
		file_proto_cliente_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_cliente_proto_rawDescData)
	})
	return file_proto_cliente_proto_rawDescData
}

var file_proto_cliente_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cliente_proto_goTypes = []interface{}{
	(*ClienteRequest)(nil),  // 0: cliente.ClienteRequest
	(*ClienteResponse)(nil), // 1: cliente.ClienteResponse
}
var file_proto_cliente_proto_depIdxs = []int32{
	0, // 0: cliente.ClienteService.EnviarCliente:input_type -> cliente.ClienteRequest
	1, // 1: cliente.ClienteService.EnviarCliente:output_type -> cliente.ClienteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cliente_proto_init() }
func file_proto_cliente_proto_init() {
	if File_proto_cliente_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_cliente_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClienteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cliente_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClienteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_cliente_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cliente_proto_goTypes,
		DependencyIndexes: file_proto_cliente_proto_depIdxs,
		MessageInfos:      file_proto_cliente_proto_msgTypes,
	}.Build()
	File_proto_cliente_proto = out.File
	file_proto_cliente_proto_rawDesc = nil
	file_proto_cliente_proto_goTypes = nil
	file_proto_cliente_proto_depIdxs = nil
}
