// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package disciplina

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DisciplinaServiceClient is the client API for DisciplinaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DisciplinaServiceClient interface {
	ProcesarAlumno(ctx context.Context, in *AlumnoRequest, opts ...grpc.CallOption) (*AlumnoResponse, error)
}

type disciplinaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDisciplinaServiceClient(cc grpc.ClientConnInterface) DisciplinaServiceClient {
	return &disciplinaServiceClient{cc}
}

func (c *disciplinaServiceClient) ProcesarAlumno(ctx context.Context, in *AlumnoRequest, opts ...grpc.CallOption) (*AlumnoResponse, error) {
	out := new(AlumnoResponse)
	err := c.cc.Invoke(ctx, "/disciplina.DisciplinaService/ProcesarAlumno", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisciplinaServiceServer is the server API for DisciplinaService service.
// All implementations must embed UnimplementedDisciplinaServiceServer
// for forward compatibility
type DisciplinaServiceServer interface {
	ProcesarAlumno(context.Context, *AlumnoRequest) (*AlumnoResponse, error)
	mustEmbedUnimplementedDisciplinaServiceServer()
}

// UnimplementedDisciplinaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDisciplinaServiceServer struct {
}

func (UnimplementedDisciplinaServiceServer) ProcesarAlumno(context.Context, *AlumnoRequest) (*AlumnoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcesarAlumno not implemented")
}
func (UnimplementedDisciplinaServiceServer) mustEmbedUnimplementedDisciplinaServiceServer() {}

// UnsafeDisciplinaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisciplinaServiceServer will
// result in compilation errors.
type UnsafeDisciplinaServiceServer interface {
	mustEmbedUnimplementedDisciplinaServiceServer()
}

func RegisterDisciplinaServiceServer(s grpc.ServiceRegistrar, srv DisciplinaServiceServer) {
	s.RegisterService(&DisciplinaService_ServiceDesc, srv)
}

func _DisciplinaService_ProcesarAlumno_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlumnoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisciplinaServiceServer).ProcesarAlumno(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disciplina.DisciplinaService/ProcesarAlumno",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisciplinaServiceServer).ProcesarAlumno(ctx, req.(*AlumnoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DisciplinaService_ServiceDesc is the grpc.ServiceDesc for DisciplinaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DisciplinaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "disciplina.DisciplinaService",
	HandlerType: (*DisciplinaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcesarAlumno",
			Handler:    _DisciplinaService_ProcesarAlumno_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "disciplina.proto",
}
