// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cliente

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClienteServiceClient is the client API for ClienteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClienteServiceClient interface {
	EnviarCliente(ctx context.Context, in *ClienteRequest, opts ...grpc.CallOption) (*ClienteResponse, error)
}

type clienteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClienteServiceClient(cc grpc.ClientConnInterface) ClienteServiceClient {
	return &clienteServiceClient{cc}
}

func (c *clienteServiceClient) EnviarCliente(ctx context.Context, in *ClienteRequest, opts ...grpc.CallOption) (*ClienteResponse, error) {
	out := new(ClienteResponse)
	err := c.cc.Invoke(ctx, "/cliente.ClienteService/EnviarCliente", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClienteServiceServer is the server API for ClienteService service.
// All implementations must embed UnimplementedClienteServiceServer
// for forward compatibility
type ClienteServiceServer interface {
	EnviarCliente(context.Context, *ClienteRequest) (*ClienteResponse, error)
	mustEmbedUnimplementedClienteServiceServer()
}

// UnimplementedClienteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClienteServiceServer struct {
}

func (UnimplementedClienteServiceServer) EnviarCliente(context.Context, *ClienteRequest) (*ClienteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarCliente not implemented")
}
func (UnimplementedClienteServiceServer) mustEmbedUnimplementedClienteServiceServer() {}

// UnsafeClienteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClienteServiceServer will
// result in compilation errors.
type UnsafeClienteServiceServer interface {
	mustEmbedUnimplementedClienteServiceServer()
}

func RegisterClienteServiceServer(s grpc.ServiceRegistrar, srv ClienteServiceServer) {
	s.RegisterService(&ClienteService_ServiceDesc, srv)
}

func _ClienteService_EnviarCliente_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClienteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClienteServiceServer).EnviarCliente(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cliente.ClienteService/EnviarCliente",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClienteServiceServer).EnviarCliente(ctx, req.(*ClienteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClienteService_ServiceDesc is the grpc.ServiceDesc for ClienteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClienteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cliente.ClienteService",
	HandlerType: (*ClienteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarCliente",
			Handler:    _ClienteService_EnviarCliente_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cliente.proto",
}
